[package]
name = "sima-pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
sima-core = { path = "../sima-core" }
sima-model = { path = "../sima-model" }
sima-domains = { path = "../sima-domains" }
sima-scheduler = { path = "../sima-scheduler" }
sima-store = { path = "../sima-store" }
serde.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
