[package]
name = "sima-domains"
version.workspace = true
edition.workspace = true

[dependencies]
sima-core = { path = "../sima-core" }
sima-model = { path = "../sima-model" }
sima-contracts = { path = "../sima-contracts" }
sima-toolkit-wgsl = { path = "../toolkits/sima-toolkit-wgsl" }
bytemuck.workspace = true
toml.workspace = true

[dev-dependencies]
sima-store = { path = "../sima-store" }
tempfile.workspace = true

[lints]
workspace = true
