[package]
name = "sima-toolkit-cuda"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sima-contracts = { path = "../../sima-contracts" }
sima-core = { path = "../../sima-core" }
cudarc.workspace = true
libloading.workspace = true

[dev-dependencies]
bytemuck.workspace = true

[lints]
workspace = true
