[package]
name = "sima-provider-vast"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sima-core = { path = "../../sima-core" }
sima-provider = { path = "../../sima-provider" }
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true

[lints]
workspace = true
